#pragma once
#pragma once
#define GLEW_STATIC
#include <GL/glew.h>
#include <GL/glu.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include <util/glm/glm.hpp>
#include <util/glm/gtc/constants.hpp>
#include <util/glm/trigonometric.hpp>
#include "renderer/gl/shader.h"
#include "renderer/gl/glErrors.h"